apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: xdarkn/taskapp:web:web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          # imagePullPolicy: Always