apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
          command: ["apt update", "apt install curl", "curl -O https://downloads.mongodb.com/compass/mongosh-1.10.6-linux-x64.tgz", "tar -zxvf mongosh-1.10.6-linux-x64.tgz", "cd mongosh-1.10.6-linux-x64/bin"]
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc