name: build-test-push-workflow
on:
  pull_request:
    branches:
      - main
  repository_dispatch:
    types:
    - trigger-config

jobs:
  Build-Push:
    runs-on: ubuntu-20.04
    name: build example and deploy to minikube
    steps:
      - name: clone application from github repo.
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'xDarkN/TaskM_App'
          platform: 'github'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
      - name: build docker image
        run: |
          docker build -t xdarkn/taskapp:v1.0.${{ github.run_id }} .
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: docker push
        run: |
          docker push xdarkn/taskapp:v1.0.${{ github.run_id }}

      - name: checkout
        uses: actions/checkout@v3

      - name: Update Deployment Manifest
        run: |
          sed -i "s|image: xdarkn/taskapp:v1.0.*|image: xdarkn/taskapp:v1.0.${{ github.run_id }}|" k8s/taskapp.yaml

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster !
        run: kubectl get pods -A        
      - name: Deploy to minikube
        run: |
          cd k8s
          kubectl apply -f mongo.yaml
          kubectl apply -f mongo-svc.yaml
          kubectl apply -f mongo-pv.yaml
          kubectl apply -f mongo-pvc.yaml
          kubectl apply -f taskapp.yaml
          kubectl apply -f taskapp-svc.yaml
      - name: Take a nap
        run: sleep 50
      - name: Test service URLs
        run: |
          docker images
          minikube service list
          kubectl get pods
          minikube service tasksapp-svc --url
          echo "-----------------opening the service-----------------"
          
      # - name: docker push
      #   run: |
      #     docker tag xdarkn/taskapp:latest xdarkn/taskapp:v1.0.${{ github.run_id }}
      #     docker push xdarkn/taskapp:v1.0.${{ github.run_id }}




      # - name: push to github
      #   uses: github-actions-x/commit@v2.9
      #   with:
      #     github-token: ${{ secrets.ACTIONS_KEY }}
      #     push-branch: 'main'
      #     commit-message: 'publish'
      #     force-add: 'true'
      #     files: k8s/taskapp.yaml
      #     name: Tomer
      #     email: tomershalev9@gmail.com

      # - name: Commit and Push Changes
      #   run: |
      #     git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
      #     git config --global user.name "${{ secrets.GIT_USER_NAME }}"
      #     git add k8s/taskapp.yaml
      #     git commit -m "Update image tag in k8s/taskapp.yaml"
      #     git push origin main
  
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_KEY }}
          BRANCH_NAME: 'main'
