name: build-test-push-workflow
on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
    - trigger-config

jobs:
  Build-Push:
    runs-on: ubuntu-20.04
    name: build example and deploy to minikube
    steps:
      - name: clone application from github repo.
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'xDarkN/TaskM_App'
          platform: 'github'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
      - name: build docker image
        run: |
          docker build -t xdarkn/taskapp:latest .
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: docker push
        run: |
          docker push xdarkn/taskapp:latest

      - name: checkout
        uses: actions/checkout@v3

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster !
        run: kubectl get pods -A        
      - name: Deploy to minikube
        run: |
          cd k8s
          kubectl apply -f mongo.yaml
          kubectl apply -f mongo-svc.yaml
          kubectl apply -f mongo-pv.yaml
          kubectl apply -f mongo-pvc.yaml
          kubectl apply -f webapp.yaml
          kubectl apply -f webapp-svc.yaml
      - name: Take a nap
        run: sleep 30
      - name: Test service URLs
        run: |
          docker images
          minikube service list
          kubectl get pods
          minikube service webapp-svc --url
          echo "-----------------opening the service-----------------"
          
      - name: docker push
        run: |
          docker tag xdarkn/taskapp:latest xdarkn/taskapp:v1.0.${{ github.run_id }}
          docker push xdarkn/taskapp:v1.0.${{ github.run_id }}
